require('./helpers/register-ts.cjs')
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),fs=require('node:fs'),path=require('node:path')
const originalLoad=Module._load, owner='11111111-1111-4111-8111-111111111111';let signups=0,bannedUntil=null,adminFails=false
Object.assign(process.env,{NEXT_PUBLIC_SUPABASE_URL:"https://fixture.invalid",NEXT_PUBLIC_SUPABASE_ANON_KEY:"synthetic-anon",SUPABASE_SERVICE_ROLE_KEY:["synthetic","private"].join("-")})
Module._load=function(id,...args){if(id==='@supabase/supabase-js')return {createClient:()=>({auth:{admin:{getUserById:async()=>({data:{user:{id:owner,email:'existing@example.invalid',banned_until:bannedUntil}},error:adminFails?{message:'private failure'}:null})},signUp:async()=>{signups++;return {data:{user:{id:owner}},error:null}},signInWithPassword:async()=>({data:{user:{id:owner,email:'existing@example.invalid',user_metadata:{}},session:{}},error:null})}})};return originalLoad.call(this,id,...args)}
const {authOptions}=require('../src/lib/auth/auth.ts'),{POST:register}=require('../src/app/api/auth/register/route.ts')
Module._load=originalLoad
const {NextRequest}=require('next/server'),{createMobileSessionToken,verifyMobileSessionToken,MOBILE_SESSION_DURATION_SECONDS}=require('../src/lib/auth/mobile-session.ts'),{POST:refresh}=require('../src/app/api/mobile/refresh/route.ts')
const saved={...process.env};process.env.NEXTAUTH_SECRET='synthetic-auth-fixture-signing-secret';delete process.env.AUTH_SESSION_NOT_BEFORE;delete process.env.AUTH_GOOGLE_ACCOUNTS;delete process.env.AUTH_SESSION_REGISTRY_ENABLED
const req=()=>new NextRequest('https://fixture.invalid/api/auth/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({firstName:'Synthetic',lastName:'User',email:'new@example.invalid',password:'synthetic-pass'})})
test('public registration is blocked before creating any account',async()=>{const r=await register(req());assert.equal(r.status,403);assert.equal(signups,0)})
test('existing password account can still log in',async()=>{const provider=authOptions.providers.find(p=>p.id==='credentials');const user=await provider.options.authorize({email:'existing@example.invalid',password:'synthetic-pass'},{});assert.equal(user.id,owner)})
test('Google admission is denied without an explicit verified account mapping',async()=>{const input={user:{id:'google-subject',email:'foreign@example.invalid'},account:{provider:'google'},profile:{email:'foreign@example.invalid',email_verified:true}};assert.equal(await (authOptions.callbacks.signIn?.(input)??true),false)})
test('Google admitted only for exact verified email and mapped Supabase UUID',async()=>{process.env.AUTH_GOOGLE_ACCOUNTS=JSON.stringify({'existing@example.invalid':owner});try{for(const verified of [false,'true',undefined])assert.equal(await(authOptions.callbacks.signIn?.({user:{id:'subject',email:'existing@example.invalid'},account:{provider:'google'},profile:{email:'existing@example.invalid',email_verified:verified}})??true),false);const user={id:'subject',email:'existing@example.invalid'};assert.equal(await(authOptions.callbacks.signIn?.({user,account:{provider:'google'},profile:{email:'existing@example.invalid',email_verified:true}})??false),true);assert.equal(user.id,owner)}finally{delete process.env.AUTH_GOOGLE_ACCOUNTS}})
test('Google rejects banned accounts and unavailable identity state',async()=>{Object.assign(process.env,{AUTH_GOOGLE_ACCOUNTS:JSON.stringify({'existing@example.invalid':owner})});const input=()=>({user:{id:'subject',email:'existing@example.invalid'},account:{provider:'google'},profile:{email:'existing@example.invalid',email_verified:true}});try{bannedUntil=new Date(Date.now()+86400000).toISOString();assert.equal(await authOptions.callbacks.signIn(input()),false);bannedUntil=null;adminFails=true;assert.equal(await authOptions.callbacks.signIn(input()),false)}finally{bannedUntil=null;adminFails=false;delete process.env.AUTH_GOOGLE_ACCOUNTS}})
test('mobile rolling refresh cannot extend session beyond thirty days',async()=>{const original=Date.now;let clock=1800000000000;Date.now=()=>clock;try{let {token}=createMobileSessionToken({id:owner});let stopped=false;for(let i=0;i<12;i++){clock+=(MOBILE_SESSION_DURATION_SECONDS-60)*1000;const r=await refresh(new NextRequest('https://fixture.invalid/api/mobile/refresh',{method:'POST',headers:{authorization:'Bearer '+token}}));if(r.status===401){stopped=true;break}assert.equal(r.status,200);token=(await r.json()).access_token}assert.equal(stopped,true,'Rolling refresh currently never reaches an absolute deadline')}finally{Date.now=original}})
test('mobile expiry metadata matches the clipped absolute deadline',()=>{const now=Math.floor(Date.now()/1000),s=createMobileSessionToken({id:owner},{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',startedAt:now-29*86400});assert.equal(s.expiresIn,s.expiresAt-now)})
test('global revocation rejects older mobile tokens and new login is still usable',()=>{const original=Date.now;Date.now=()=>1800000000000;try{const old=createMobileSessionToken({id:owner}).token;process.env.AUTH_SESSION_NOT_BEFORE=new Date(Date.now()+1000).toISOString();assert.equal(verifyMobileSessionToken(old).valid,false);Date.now=()=>1800000002000;assert.equal(verifyMobileSessionToken(createMobileSessionToken({id:owner}).token).valid,true)}finally{delete process.env.AUTH_SESSION_NOT_BEFORE;Date.now=original}})
test('web callback does not keep legacy or globally revoked sessions authenticated',async()=>{const original=Date.now;Date.now=()=>1800000000000;try{const token=await authOptions.callbacks.jwt({token:{},user:{id:owner,email:'existing@example.invalid',name:'Existing'},account:{provider:'credentials'}});assert.equal(token.id,owner);process.env.AUTH_SESSION_NOT_BEFORE=new Date(Date.now()+1000).toISOString();const expired=await authOptions.callbacks.jwt({token});assert.equal(Boolean(expired.id),false);const legacy=await authOptions.callbacks.jwt({token:{id:owner}});assert.equal(Boolean(legacy.id),false)}finally{Date.now=original;delete process.env.AUTH_SESSION_NOT_BEFORE}})
test('session migration enforces owner revocation and denies public roles (isolated PostgreSQL)',async()=>{const file=path.join(__dirname,'../supabase/migrations/20261004_app_auth_sessions.sql');assert.ok(fs.existsSync(file),'Session registry migration is missing');const {PGlite}=require('@electric-sql/pglite'),db=new PGlite();try{await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key,encrypted_password text,banned_until timestamptz);INSERT INTO auth.users(id) VALUES ('${owner}'),('22222222-2222-4222-8222-222222222222');`);const sql=fs.readFileSync(file,'utf8');await db.exec(sql);await db.exec(sql);await db.query("INSERT INTO public.app_auth_sessions(id,user_id,expires_at) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',$1,now()+interval '1 day'),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','22222222-2222-4222-8222-222222222222',now()+interval '1 day')",[owner]);await db.query('UPDATE public.app_auth_sessions SET revoked_at=now() WHERE user_id=$1',[owner]);assert.equal((await db.query('SELECT count(*)::int AS n FROM public.app_auth_sessions WHERE revoked_at IS NULL')).rows[0].n,1);for(const role of ['anon','authenticated']){await db.exec('SET ROLE '+role);await assert.rejects(()=>db.query('SELECT * FROM public.app_auth_sessions'),/permission denied/);await db.exec('RESET ROLE')}}finally{await db.close()}})
