require('./helpers/register-ts.cjs')
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),fs=require('node:fs'),path=require('node:path')
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',sid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
let user=owner,dbFails=false,records=[],queries=[],creates=0
const originalEnvSetup = Object.assign(process.env, { NEXT_PUBLIC_SUPABASE_URL: 'https://fixture.invalid', NEXT_PUBLIC_SUPABASE_ANON_KEY: 'synthetic-anon' })
const load=Module._load
Module._load=function(id,...args){if(id==='next-auth')return {getServerSession:async()=>user?{user:{id:user}}:null};if(id==='@supabase/supabase-js')return {createClient:()=>{creates++;return {from:table=>{const where=[];let operation='read',value;const q={select(){return q},eq(...a){where.push(['eq',...a]);return q},is(...a){where.push(['is',...a]);return q},gt(...a){where.push(['gt',...a]);return q},insert(v){operation='insert';value=v;return q},update(v){operation='update';value=v;return q},maybeSingle(){return q},then(ok,fail){queries.push({table,where,operation});if(dbFails)return Promise.resolve({error:{message:'PRIVATE ERROR'},data:null}).then(ok,fail);if(operation==='insert')records.push(value);const selected=records.filter(r=>where.every(([op,k,v])=>op==='eq'?r[k]===v:op==='is'?(r[k]??null)===v:r[k]>v));if(operation==='update')selected.forEach(r=>Object.assign(r,value));return Promise.resolve({error:null,data:selected[0]??null}).then(ok,fail)}};return q}}}};return load.call(this,id,...args)}
const registry=require('../src/lib/auth/session-registry.ts')
const {authOptions}=require('../src/lib/auth/auth.ts'),{POST:refresh}=require('../src/app/api/mobile/refresh/route.ts')
const file=path.join(__dirname,'../src/app/api/auth/sessions/route.ts'),route=fs.existsSync(file)?require(file):{}
const {getAuthenticatedSupabaseClient}=require('../src/lib/auth/auth-supabase.ts'),mobile=require('../src/lib/auth/mobile-session.ts')
Module._load=load
process.env.NEXT_PUBLIC_SUPABASE_URL='https://fixture.invalid';process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='synthetic-anon';process.env.SUPABASE_SERVICE_ROLE_KEY='synthe...ivate';process.env.NEXTAUTH_URL='https://fixture.invalid';process.env.NEXTAUTH_SECRET='synthe...cret';Object.assign(process.env, { AUTH_SESSION_REGISTRY_ENABLED: String(true) });
const request=origin=>new Request('https://fixture.invalid/api/auth/sessions',{method:'POST',headers:{'content-type':'application/json',...(origin?{origin}:{})}})
function reset(){user=owner;dbFails=false;queries=[];records=[{id:sid,user_id:owner,revoked_at:null,expires_at:new Date(Date.now()+86400000).toISOString()},{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',user_id:other,revoked_at:null,expires_at:new Date(Date.now()+86400000).toISOString()}]}
test('revoke endpoint rejects anonymous requests before database access',async()=>{assert.equal(typeof route.POST,'function','Revocation handler missing');reset();user=null;const r=await route.POST(request('https://fixture.invalid'));assert.equal(r.status,401);assert.equal(queries.length,0)})
test('revoke endpoint rejects absent/foreign Origin and non-JSON before changes',async()=>{assert.equal(typeof route.POST,'function');for(const origin of [null,'https://evil.invalid','null']){reset();assert.equal((await route.POST(request(origin))).status,403);assert.equal(queries.length,0)}reset();assert.equal((await route.POST(new Request('https://fixture.invalid/api/auth/sessions',{method:'POST',headers:{origin:'https://fixture.invalid','content-type':'text/plain'}}))).status,415)})
test('revoke endpoint revokes owner only; same signed session fails API and refresh afterward',async()=>{assert.equal(typeof route.POST,'function');reset();const startedAt=Math.floor(Date.now()/1000),token=mobile.createMobileSessionToken({id:owner},{id:sid,startedAt}).token;assert.equal(await registry.authSessionActive(owner,sid,startedAt),true);const r=await route.POST(request('https://fixture.invalid'));assert.equal(r.status,200);assert.ok(records[0].revoked_at);assert.equal(records[1].revoked_at,null);assert.equal(await registry.authSessionActive(owner,sid,startedAt),false);const result=await getAuthenticatedSupabaseClient(new Request('https://fixture.invalid/api/gastos',{headers:{authorization:'Bearer '+token}}));assert.equal(result.error.status,401);assert.equal((await refresh(new Request('https://fixture.invalid/api/mobile/refresh',{method:'POST',headers:{authorization:'Bearer '+token}}))).status,401);assert.ok(queries.some(q=>q.operation==='update'&&q.where.some(w=>w[1]==='user_id'&&w[2]===owner)))})
test('status and failure do not expose database diagnostics',async()=>{assert.equal(typeof route.GET,'function');reset();assert.equal((await (await route.GET()).json()).revocationEnabled,true);dbFails=true;const r=await route.POST(request('https://fixture.invalid'));assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/PRIVATE ERROR/);assert.equal(await registry.authSessionActive(owner,sid,Math.floor(Date.now()/1000)),false)})
test('registry disabled reports unavailable rather than fake revocation',async()=>{assert.equal(typeof route.POST,'function');reset();delete process.env.AUTH_SESSION_REGISTRY_ENABLED;try{assert.equal((await route.POST(request('https://fixture.invalid'))).status,503);assert.equal(queries.length,0)}finally{Object.assign(process.env, { AUTH_SESSION_REGISTRY_ENABLED: String(true) })}})
test('registry validates expiry, ownership and revocation and records new sessions',async()=>{reset();const startedAt=Math.floor(Date.now()/1000);assert.equal(await registry.authSessionActive(other,sid,startedAt),false);records[0].expires_at=new Date(Date.now()-1000).toISOString();assert.equal(await registry.authSessionActive(owner,sid,startedAt),false);const id=await registry.registerAuthSession(owner,startedAt);assert.equal(await registry.authSessionActive(owner,id,startedAt),true)})
test('web JWT callback rejects a revoked registry session',async()=>{reset();const token=await authOptions.callbacks.jwt({token:{},user:{id:owner,email:'existing@example.invalid'},account:{provider:'credentials'}});assert.equal(token.id,owner);await registry.revokeUserSessions(owner);assert.equal(Boolean((await authOptions.callbacks.jwt({token})).id),false)})
test('legacy provider bearer cannot bypass registry-based revocation',async()=>{reset();const r=await getAuthenticatedSupabaseClient(new Request('https://fixture.invalid/api/gastos',{headers:{authorization:'Bearer legacy-provider-token'}}));assert.equal(r.error.status,401)})
