require('./helpers/register-ts.cjs')
const test = require('node:test')
const assert = require('node:assert/strict')
const React = require('react')
const { renderToStaticMarkup } = require('react-dom/server')
const { ProjectionCard } = require('../src/components/stats/projection-card.tsx')
const { buildExpenseForecast } = require('../src/lib/expense-forecast.ts')
const render = forecast => renderToStaticMarkup(React.createElement(ProjectionCard, { forecast, proyeccion: { proyectado: 310, ritmoDiario: 10, diasTranscurridos: 8, diasTotales: 31, totalPrevio: 0, deltaVsPrevio: null } }))
test('separa lo registrado de las estimaciones y no promete una precisión sin medir', () => {
  const forecast = buildExpenseForecast({ today: '2026-10-08', expenses: Array.from({ length: 7 }, (_, i) => ({ fecha: `2026-10-0${i + 1}`, monto: 10 })), rules: [] })
  const html = render(forecast)
  assert.match(html, /Registrado hasta hoy/)
  assert.match(html, /Recurrentes por registrar/)
  assert.match(html, /Variable por estimar/)
  assert.match(html, /Estimación inicial/)
  assert.match(html, /No hay suficientes meses/)
  assert.doesNotMatch(html, /95%|90%|Alta confianza|Sin riesgo/)
})
test('sin historial no muestra un cierre de cero y permite ver el mínimo conocido', () => {
  const html = render(buildExpenseForecast({ today: '2026-10-01', expenses: [], rules: [] }))
  assert.match(html, /Historial insuficiente/)
  assert.match(html, /Mínimo conocido/)
  assert.doesNotMatch(html, /Cerrarías el mes en/)
})
