require('./helpers/register-ts.cjs')
const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
function state(){const p=require('node:path').resolve(__dirname,'../src/lib/expense-filter-state.ts');assert.ok(fs.existsSync(p),'Missing validated account-scoped filter persistence');return require(p)}
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}}
test('filter persistence restores values only for the same account',()=>{const s=state(),db=storage();s.writeExpenseFilters(db,'a',{...s.initialFilters,search:'café',category:'8',sortBy:'amount'});assert.equal(s.readExpenseFilters(db,'a').search,'café');assert.equal(s.readExpenseFilters(db,'a').sortBy,'amount');assert.equal(s.readExpenseFilters(db,'b').search,'');assert.equal(s.readExpenseFilters(db,undefined).search,'')})
test('malformed and blocked storage fall back safely',()=>{const s=state();assert.deepEqual(s.readExpenseFilters({getItem:()=>'{broken'},'a'),s.initialFilters);assert.deepEqual(s.readExpenseFilters({getItem:()=>{throw Error('blocked')}},'a'),s.initialFilters);assert.doesNotThrow(()=>s.writeExpenseFilters({setItem:()=>{throw Error('blocked')}},'a',s.initialFilters))})
test('restored controls validate enums, dates, IDs and numeric fields',()=>{const s=state();const result=s.normalizeExpenseFilters({search:'café',sortBy:'__proto__',groupBy:'invalid',dateRange:'custom',dateFrom:'2026-02-31',dateTo:'2026-10-09',category:'-3',paymentMethod:'2',minAmount:'NaN',maxAmount:'Infinity',sortOrder:'invalid',year:'2026'});assert.equal(result.search,'café');assert.equal(result.sortBy,'date');assert.equal(result.groupBy,'none');assert.equal(result.category,'');assert.equal(result.paymentMethod,'2');assert.equal(result.dateFrom,'');assert.equal(result.dateTo,'2026-10-09');assert.equal(result.minAmount,'');assert.equal(result.maxAmount,'')})
test('filter counts exclude inactive dates and years as well as sorting and grouping',()=>{const s=state();assert.equal(s.countActiveExpenseFilters({...s.initialFilters,dateFrom:'2026-10-02',year:'2025',sortBy:'amount',groupBy:'month'}),0);assert.equal(s.countActiveExpenseFilters({...s.initialFilters,dateRange:'custom',dateFrom:'2026-10-02',dateTo:'2026-10-10',search:'comida',category:'2'}),3)})
