require('./helpers/register-ts.cjs')
const { test } = require('node:test')
const assert = require('node:assert/strict')
const React = require('react')
const { renderToStaticMarkup } = require('react-dom/server')
const { computeForeignTax, validateForeignTax, withForeignTag, emptyForeignTax } = require('../src/lib/foreign-tax.ts')
const { ForeignTaxField } = require('../src/components/gastos/ForeignTaxField.tsx')
const on = (selected, customRate = '') => ({ enabled: true, selected, customRate })

test('desactivado no cambia el monto', () => {
  assert.equal(computeForeignTax(10, emptyForeignTax()).total, 10)
})
test('ISD 5% y IVA digital 15% se calculan sobre el precio original y se suman', () => {
  assert.deepEqual(computeForeignTax(10, on(['isd'])).total, 10.5)
  assert.deepEqual(computeForeignTax(10, on(['iva_digital'])).total, 11.5)
  const both = computeForeignTax(15.99, on(['isd', 'iva_digital']))
  assert.deepEqual(both.lines.map(line => line.amount), [0.8, 2.4])
  assert.equal(both.taxTotal, 3.2)
  assert.equal(both.total, 19.19)
})
test('porcentaje personalizado acepta coma decimal y se valida', () => {
  assert.equal(computeForeignTax(100, on(['custom'], '2,5')).total, 102.5)
  assert.match(validateForeignTax(on(['custom'], '0')), /porcentaje/)
  assert.match(validateForeignTax(on([])), /al menos un impuesto/)
  assert.equal(validateForeignTax(on(['isd'])), null)
})
test('agrega #exterior una sola vez y respeta el límite de etiquetas', () => {
  assert.deepEqual(withForeignTag(['viaje'], on(['isd'])), ['viaje', 'exterior'])
  assert.deepEqual(withForeignTag(['exterior'], on(['isd'])), ['exterior'])
  assert.deepEqual(withForeignTag([], emptyForeignTax()), [])
  assert.equal(withForeignTag(Array.from({ length: 10 }, (_, i) => `t${i}`), on(['isd'])).length, 10)
})
test('el campo muestra el desglose con el total que se guarda', () => {
  const html = renderToStaticMarkup(React.createElement(ForeignTaxField, { base: 20, value: on(['isd', 'iva_digital']), onChange() {} }))
  assert.match(html, /Compra en el exterior/)
  assert.match(html, /Salida de divisas/)
  assert.match(html, /IVA servicios digitales/)
  assert.match(html, /\$24\.00/)
})
