require('./helpers/register-ts.cjs')
const { test } = require('node:test')
const assert = require('node:assert/strict')
const React = require('react')
const { renderToStaticMarkup } = require('react-dom/server')
const { BudgetSummary } = require('../src/components/presupuesto/BudgetSummary.tsx')
const { buildMonthPlan } = require('../src/lib/month-planning.ts')
const planning = () => require('../src/components/dashboard/MonthPlanning.tsx')
const render = (component, props) => renderToStaticMarkup(React.createElement(component, props))
const fixture = (overrides = {}) => buildMonthPlan({ today:'2026-10-02', budget:1000, expenses:[], categories:[], rules:[], ...overrides })
test('shared budget summary preserves its existing labels and amounts without planning', () => {
  const html = render(BudgetSummary,{presupuestado:1000,gastado:100})
  assert.match(html,/Disponible/); assert.match(html,/\$900\.00/); assert.doesNotMatch(html,/Recurrentes por reservar|Guía diaria/)
})
test('planning uses the shared summary, distinguishes negative available from spent overshoot', () => {
  const html = render(BudgetSummary,{presupuestado:100,gastado:75, planning:{committed:50,available:-25,daily:0,daysLeft:30}})
  assert.match(html,/Exceso previsto/); assert.match(html,/\$25\.00/); assert.match(html,/Recurrentes por reservar/); assert.match(html,/Guía diaria/)
  assert.match(html,/75% del presupuesto consumido/)
})
test('upcoming rows show five items initially and keep all the others in a native disclosure', () => {
  const rules = Array.from({length:8},(_,i)=>({id:i+1,descripcion:`Cargo ${i+1}`,monto:10,activo:true,frecuencia:'mensual',dia_mes:10,fecha_inicio:'2026-01-01'}))
  const html = render(planning().MonthPlanning,{plan:fixture({rules}),loading:false,error:null})
  assert.equal((html.match(/<time /g)||[]).length,8)
  assert.match(html,/<details/); assert.match(html,/<summary/); assert.match(html,/Ver 3 más/)
  assert.equal((html.match(/Próximos recurrentes<\/div>/g)||[]).length,1)
})
test('empty and no-budget states stay compact with an actionable budget link', () => {
  const p = fixture({budget:undefined})
  const html = render(planning().MonthPlanningSummary,{plan:p,loading:false,error:null})
  assert.match(html,/href="\/presupuesto"/); assert.match(html,/Crear presupuesto/); assert.doesNotMatch(html,/Guía diaria|\$0\.00/)
  const details = render(planning().MonthPlanning,{plan:p,loading:false,error:null})
  assert.match(details,/Sin cargos próximos/); assert.match(details,/Configura límites/)
})
test('alert rows use concise titles and supporting values rather than nested cards', () => {
  const html = render(planning().MonthPlanning,{plan:fixture({categories:[{id:1,nombre:'Comida',presupuestado:100,gastado:85}]}),loading:false,error:null})
  assert.match(html,/Comida/); assert.match(html,/Quedan \$15\.00/); assert.doesNotMatch(html,/bg-muted\/30|Revisa sus gastos o ajusta/)
})
