const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { PGlite } = require('@electric-sql/pglite')
const migration = path.join(__dirname, '../supabase/migrations/20261003_recurring_single_cron.sql')
async function setup(legacy = false) {
  assert.ok(fs.existsSync(migration), 'Falta la migración del cron único')
  const db = new PGlite()
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
    CREATE TABLE gasto_recurrente(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id uuid NOT NULL,descripcion text NOT NULL,monto numeric NOT NULL,categoria_id integer NOT NULL,metodo_pago_id integer NOT NULL,frecuencia text NOT NULL,dia_mes bigint,dia_semana bigint,fecha_inicio date NOT NULL,fecha_fin date,activo boolean NOT NULL DEFAULT true);
    CREATE TABLE gasto(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id uuid NOT NULL,descripcion text NOT NULL,monto numeric NOT NULL,categoria_id integer NOT NULL,metodo_pago_id integer NOT NULL,fecha date NOT NULL,is_recurrent boolean NOT NULL DEFAULT false);
    CREATE TABLE gasto_recurrente_instancia(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,gasto_recurrente_id bigint REFERENCES gasto_recurrente(id),gasto_id bigint REFERENCES gasto(id) ON DELETE SET NULL,fecha_programada date NOT NULL,estado text NOT NULL,generado_en timestamptz);`)
  if (legacy) await db.exec(`INSERT INTO gasto_recurrente VALUES(10,'11111111-1111-4111-8111-111111111111','Internet',30,1,1,'mensual',5,NULL,'2020-01-05',NULL,true);
    INSERT INTO gasto VALUES(101,'11111111-1111-4111-8111-111111111111','Internet',30,1,1,'2025-09-05',true),(102,'11111111-1111-4111-8111-111111111111','Internet',30,1,1,'2025-09-05',true);
    INSERT INTO gasto_recurrente_instancia(gasto_recurrente_id,gasto_id,fecha_programada,estado) VALUES(10,101,'2025-09-05','generado'),(10,102,'2025-09-05','generado'),(10,NULL,'2030-01-05','pendiente');`)
  try { await db.exec(fs.readFileSync(migration, 'utf8')) }
  catch (error) { await db.close(); throw error }
  return db
}
async function rule(db, frequency='mensual', start='2030-01-01', end=null, active=true) {
  return (await db.query(`INSERT INTO gasto_recurrente(user_id,descripcion,monto,categoria_id,metodo_pago_id,frecuencia,dia_mes,dia_semana,fecha_inicio,fecha_fin,activo) VALUES('11111111-1111-4111-8111-111111111111','Prueba',30,1,1,$1,$2,$3,$4,$5,$6) RETURNING id`,[frequency,frequency==='mensual'?5:null,frequency==='semanal'?1:null,start,end,active])).rows[0].id
}
const processDue = async (db, date, limit=200) => (await db.query('SELECT process_recurring_expenses($1::date,$2) AS result',[date,limit])).rows[0].result
const count = async db => (await db.query('SELECT count(*)::int AS n FROM gasto')).rows[0].n

test('PostgreSQL: creation stores only a rule, start/end bound the calendar, weekly dates cover the full month',async()=>{
  const db=await setup();try {
    await rule(db,'mensual','2030-02-06'); await rule(db,'semanal','2030-01-01','2030-01-31'); await rule(db,'mensual','2030-01-01',null,false)
    assert.equal(await count(db),0)
    assert.equal((await processDue(db,'2030-01-31')).created,4)
    assert.deepEqual((await db.query("SELECT fecha::text AS fecha FROM gasto ORDER BY fecha")).rows.map(r=>r.fecha),['2030-01-07','2030-01-14','2030-01-21','2030-01-28'])
    assert.equal((await processDue(db,'2030-03-05')).created,1)
    assert.equal((await db.query("SELECT fecha::text AS fecha FROM gasto ORDER BY fecha DESC LIMIT 1")).rows[0].fecha,'2030-03-05')
  } finally {await db.close()}
})
test('PostgreSQL: retries, bounded catch-up and deleted expenses do not replay consumed dates',async()=>{
  const db=await setup();try {
    const id=await rule(db)
    assert.equal((await processDue(db,'2030-03-05',1)).created,1)
    assert.equal((await processDue(db,'2030-03-05',1)).pending,true)
    assert.equal((await processDue(db,'2030-03-05',1)).created,1)
    assert.equal((await processDue(db,'2030-03-05')).created,0)
    await db.exec('DELETE FROM gasto')
    await db.exec(fs.readFileSync(migration, 'utf8'))
    assert.equal((await processDue(db,'2030-03-05')).created,0, 'Reaplicar la migración no debe reiniciar fechas consumidas')
    await db.query('UPDATE gasto_recurrente SET dia_mes=6 WHERE id=$1',[id])
    assert.equal((await processDue(db,'2030-03-05')).created,0)
    assert.equal((await processDue(db,'2030-03-06')).created,1)
  } finally {await db.close()}
})
test('PostgreSQL: a late insertion failure rolls back expenses AND cursor, then retry succeeds',async()=>{
  const db=await setup();try {
    const id=await rule(db)
    await db.exec("ALTER TABLE gasto ADD CONSTRAINT fixture_failure CHECK(fecha <> DATE '2030-02-05')")
    await assert.rejects(()=>processDue(db,'2030-02-05'),/fixture_failure/)
    assert.equal(await count(db),0)
    assert.equal((await db.query('SELECT proxima_fecha::text AS fecha FROM gasto_recurrente WHERE id=$1',[id])).rows[0].fecha,'2030-01-05')
    await db.exec('ALTER TABLE gasto DROP CONSTRAINT fixture_failure')
    assert.equal((await processDue(db,'2030-02-05')).created,2)
  } finally {await db.close()}
})
test('PostgreSQL: migration preserves duplicate legacy history and pending schedule without replay',async()=>{
  const db=await setup(true);try {
    assert.equal(await count(db),2)
    assert.equal((await db.query('SELECT count(*)::int AS n FROM gasto_recurrente_instancia')).rows[0].n,3)
    assert.equal((await db.query('SELECT proxima_fecha::text AS fecha FROM gasto_recurrente WHERE id=10')).rows[0].fecha,'2030-01-05')
    assert.equal((await processDue(db,'2030-01-05')).created,1)
    assert.equal((await processDue(db,'2030-01-05')).created,0)
    assert.equal((await db.query('SELECT count(*)::int AS n FROM gasto WHERE gasto_recurrente_id=10')).rows[0].n,2)
  } finally {await db.close()}
})
test('PostgreSQL: calendar edits keep watermark, pause/resume skips the paused period, invalid calendars reject',async()=>{
  const db=await setup();try {
    const id=await rule(db,'mensual','2020-01-01',null,false)
    await db.query('UPDATE gasto_recurrente SET activo=true WHERE id=$1',[id])
    assert.equal((await db.query("SELECT proxima_fecha >= (now() AT TIME ZONE 'UTC')::date AS valid FROM gasto_recurrente WHERE id=$1",[id])).rows[0].valid,true)
    await assert.rejects(()=>db.query('UPDATE gasto_recurrente SET dia_mes=31 WHERE id=$1',[id]),/calendario/)
    await assert.rejects(()=>db.query("UPDATE gasto_recurrente SET frecuencia='diaria' WHERE id=$1",[id]),/calendario/)
    await assert.rejects(()=>db.query("UPDATE gasto_recurrente SET fecha_fin='2019-01-01' WHERE id=$1",[id]),/fecha/)
  } finally {await db.close()}
})
test('PostgreSQL: only service_role may generate; concurrent retries create one occurrence',async()=>{
  const db=await setup();try {
    await rule(db)
    await db.exec('SET ROLE anon')
    await assert.rejects(()=>processDue(db,'2030-01-05'),/permission denied/)
    await db.exec('RESET ROLE; SET ROLE authenticated')
    await assert.rejects(()=>processDue(db,'2030-01-05'),/permission denied/)
    await db.exec('RESET ROLE; SET ROLE service_role')
    const results=await Promise.all([processDue(db,'2030-01-05'),processDue(db,'2030-01-05')])
    assert.equal(results.reduce((n,r)=>n+r.created,0),1)
    await db.exec('RESET ROLE')
    assert.equal(await count(db),1)
  } finally {await db.close()}
})
