const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { PGlite } = require('@electric-sql/pglite')
const read = name => fs.readFileSync(path.join(__dirname, '../supabase/migrations', name), 'utf8')

// Production-like legacy schema: enum frequency and a 1-28 CHECK that the new calendar must replace.
async function setup() {
  const db = new PGlite()
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
    CREATE TYPE frecuencia_tipo AS ENUM ('semanal','mensual');
    CREATE TABLE gasto_recurrente(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id uuid NOT NULL,descripcion text NOT NULL,monto numeric NOT NULL,categoria_id integer NOT NULL,metodo_pago_id integer NOT NULL,frecuencia frecuencia_tipo NOT NULL,dia_mes bigint CHECK (dia_mes BETWEEN 1 AND 28),dia_semana bigint,fecha_inicio date NOT NULL,fecha_fin date,activo boolean NOT NULL DEFAULT true);
    CREATE TABLE gasto(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id uuid NOT NULL,descripcion text NOT NULL,monto numeric NOT NULL,categoria_id integer NOT NULL,metodo_pago_id integer NOT NULL,fecha date NOT NULL,is_recurrent boolean NOT NULL DEFAULT false);
    CREATE TABLE gasto_recurrente_instancia(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,gasto_recurrente_id bigint REFERENCES gasto_recurrente(id),gasto_id bigint REFERENCES gasto(id) ON DELETE SET NULL,fecha_programada date NOT NULL,estado text NOT NULL,generado_en timestamptz);`)
  await db.exec(read('20261003_recurring_single_cron.sql'))
  await db.exec(read('20261005_recurring_calendar_tz.sql'))
  await db.exec(read('20261006_recurring_skip_prices.sql'))
  return db
}
const rule = async (db, frecuencia, diaMes, mesAnual, start) => (await db.query(
  `INSERT INTO gasto_recurrente(user_id,descripcion,monto,categoria_id,metodo_pago_id,frecuencia,dia_mes,mes_anual,fecha_inicio) VALUES('11111111-1111-4111-8111-111111111111','Prueba',30,1,1,$1,$2,$3,$4) RETURNING id, proxima_fecha::text AS next`,
  [frecuencia, diaMes, mesAnual, start])).rows[0]
const dates = async (db, id) => (await db.query('SELECT fecha::text AS f FROM gasto WHERE gasto_recurrente_id=$1 ORDER BY fecha', [id])).rows.map(r => r.f)
const processDue = (db, date) => db.query('SELECT process_recurring_expenses($1::date) AS r', [date])

test('PostgreSQL: day 31 falls on the last day of shorter months', async () => {
  const db = await setup(); try {
    const { id } = await rule(db, 'mensual', 31, null, '2030-01-01')
    await processDue(db, '2030-04-30')
    assert.deepEqual(await dates(db, id), ['2030-01-31', '2030-02-28', '2030-03-31', '2030-04-30'])
  } finally { await db.close() }
})

test('PostgreSQL: yearly rules repeat on their month/day, including leap years', async () => {
  const db = await setup(); try {
    const r = await rule(db, 'anual', 29, 2, '2030-03-01')
    assert.equal(r.next, '2031-02-28', 'a date already past this year moves to next year')
    await processDue(db, '2032-12-31')
    assert.deepEqual(await dates(db, r.id), ['2031-02-28', '2032-02-29'])
    await assert.rejects(() => rule(db, 'anual', 10, null, '2030-01-01'), /calendario|check/i)
  } finally { await db.close() }
})

test('PostgreSQL: the local day drives the cron default and the calendar CHECK', async () => {
  const db = await setup(); try {
    const { rows } = await db.query("SELECT app_today() = (now() AT TIME ZONE 'America/Guayaquil')::date AS ok")
    assert.equal(rows[0].ok, true)
    assert.equal((await db.query('SELECT (process_recurring_expenses()->>\'date\')::date = app_today() AS ok')).rows[0].ok, true)
    await assert.rejects(() => rule(db, 'mensual', 32, null, '2030-01-01'))
    const monthly = await rule(db, 'mensual', 5, 3, '2030-01-01')
    assert.equal((await db.query('SELECT mes_anual FROM gasto_recurrente WHERE id=$1', [monthly.id])).rows[0].mes_anual, null)
    const grants = (await db.query("SELECT has_function_privilege('authenticated','process_recurring_expenses(date,integer)','EXECUTE') AS a, has_function_privilege('service_role','process_recurring_expenses(date,integer)','EXECUTE') AS s")).rows[0]
    assert.deepEqual(grants, { a: false, s: true })
  } finally { await db.close() }
})

test('PostgreSQL: skipping consumes only the next charge and stays owner-bound', async () => {
  const db = await setup(); try {
    const { id } = await rule(db, 'mensual', 8, null, '2030-01-01')
    const skip = (user) => db.query('SELECT skip_recurring_occurrence($1, $2) AS r', [id, user]).then(x => x.rows[0].r)
    assert.equal(await skip('22222222-2222-4222-8222-222222222222'), null, 'another user cannot skip it')
    assert.deepEqual(await skip('11111111-1111-4111-8111-111111111111'), { omitida: '2030-01-08', proxima_fecha: '2030-02-08' })
    await processDue(db, '2030-02-28')
    assert.deepEqual(await dates(db, id), ['2030-02-08'], 'the skipped date is never generated')
    // A paused rule has no next charge to skip.
    await db.query('UPDATE gasto_recurrente SET activo=false WHERE id=$1', [id])
    await assert.rejects(() => skip('11111111-1111-4111-8111-111111111111'), /próximo cobro/)
    const grants = (await db.query("SELECT has_function_privilege('anon','skip_recurring_occurrence(bigint,text)','EXECUTE') AS anon, has_function_privilege('service_role','skip_recurring_occurrence(bigint,text)','EXECUTE') AS svc")).rows[0]
    assert.deepEqual(grants, { anon: false, svc: true })
  } finally { await db.close() }
})

test('PostgreSQL: amount edits by the app role are logged in a table the app role cannot read', async () => {
  const db = await setup(); try {
    const { id } = await rule(db, 'mensual', 8, null, '2030-01-01')
    await db.exec('GRANT ALL ON gasto_recurrente TO anon')
    await db.exec('SET ROLE anon')
    await db.query('UPDATE gasto_recurrente SET monto=35 WHERE id=$1', [id])
    await db.query("UPDATE gasto_recurrente SET descripcion='Otra' WHERE id=$1", [id])
    await assert.rejects(() => db.query('SELECT * FROM gasto_recurrente_precio'), /permission denied/)
    await db.exec('RESET ROLE')
    const { rows } = await db.query('SELECT monto_anterior::float AS a, monto_nuevo::float AS n FROM gasto_recurrente_precio WHERE gasto_recurrente_id=$1', [id])
    assert.deepEqual(rows, [{ a: 30, n: 35 }], 'only amount changes are logged')
  } finally { await db.close() }
})
