-- Consumos leídos del correo, pendientes de revisión. Solo los aceptados se convierten en gasto.
-- Los descartados se conservan para no volver a sugerirlos al re-sincronizar.
BEGIN;

CREATE TABLE IF NOT EXISTS public.correo_consumo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  email_message_id text NOT NULL,
  origen text NOT NULL,
  fecha date NOT NULL,
  descripcion text NOT NULL,
  monto numeric(12, 2) NOT NULL CHECK (monto > 0),
  categoria_id bigint,
  metodo_pago_id bigint,
  estado text NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aceptado', 'descartado')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, email_message_id)
);
CREATE INDEX IF NOT EXISTS correo_consumo_pendientes ON public.correo_consumo(user_id, fecha DESC) WHERE estado = 'pendiente';

-- Igual que el resto de tablas de datos: solo el service role del servidor.
ALTER TABLE public.correo_consumo ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.correo_consumo FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.correo_consumo TO service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
