BEGIN;

-- 1) Skip only the next charge without pausing the rule. The skipped date is marked
-- as consumed so a later calendar edit never replays it. Called with the
-- service role after the server authenticated p_user_id: never granted to clients,
-- because the app talks to PostgREST with the public anon key.
CREATE OR REPLACE FUNCTION public.skip_recurring_occurrence(p_id bigint, p_user_id text)
RETURNS jsonb LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE r public.gasto_recurrente%ROWTYPE; next_date date;
BEGIN
  SELECT * INTO r FROM public.gasto_recurrente WHERE id = p_id AND user_id::text = p_user_id FOR UPDATE;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF NOT r.activo OR r.proxima_fecha IS NULL THEN
    RAISE EXCEPTION 'La regla no tiene un próximo cobro que saltar' USING ERRCODE = '22023';
  END IF;
  next_date := public.recurring_next_date(r.proxima_fecha + 1, r.frecuencia::text, r.dia_mes::integer, r.dia_semana::integer, r.mes_anual::integer);
  IF r.fecha_fin IS NOT NULL AND next_date > r.fecha_fin::date THEN next_date := NULL; END IF;
  UPDATE public.gasto_recurrente SET ultima_fecha_generada = r.proxima_fecha, proxima_fecha = next_date WHERE id = r.id;
  RETURN jsonb_build_object('omitida', r.proxima_fecha, 'proxima_fecha', next_date);
END $$;
REVOKE ALL ON FUNCTION public.skip_recurring_occurrence(bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.skip_recurring_occurrence(bigint, text) TO service_role;

-- 2) Price history: every amount change of a rule, read only by the server.
CREATE TABLE IF NOT EXISTS public.gasto_recurrente_precio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gasto_recurrente_id bigint NOT NULL REFERENCES public.gasto_recurrente(id) ON DELETE CASCADE,
  user_id text NOT NULL,
  monto_anterior numeric NOT NULL,
  monto_nuevo numeric NOT NULL,
  cambiado_en date NOT NULL DEFAULT public.app_today()
);
CREATE INDEX IF NOT EXISTS gasto_recurrente_precio_user ON public.gasto_recurrente_precio(user_id, cambiado_en DESC);
ALTER TABLE public.gasto_recurrente_precio ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.gasto_recurrente_precio FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON public.gasto_recurrente_precio TO service_role;

-- SECURITY DEFINER: app edits run as anon, which must not read or write the history table.
CREATE OR REPLACE FUNCTION public.recurring_log_price()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
  IF NEW.monto IS DISTINCT FROM OLD.monto THEN
    INSERT INTO public.gasto_recurrente_precio(gasto_recurrente_id, user_id, monto_anterior, monto_nuevo)
      VALUES (NEW.id, NEW.user_id::text, OLD.monto, NEW.monto);
  END IF;
  RETURN NULL;
END $$;
REVOKE ALL ON FUNCTION public.recurring_log_price() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS recurring_log_price ON public.gasto_recurrente;
CREATE TRIGGER recurring_log_price AFTER UPDATE OF monto ON public.gasto_recurrente
  FOR EACH ROW EXECUTE FUNCTION public.recurring_log_price();

NOTIFY pgrst, 'reload schema';
COMMIT;
